server:
  port: ${PORT:8080}

spring:
  application:
    name: password
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/password?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul}
    username: ${DB_USERNAME:password}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:validate}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: false

decorator:
  datasource:
    p6spy:
      enable-logging: true
      log-format: "%(executionTime)ms | %(sql)"
